/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hit.ui;

import com.hit.core.*;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author songmingye
 */
public class Lexical_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Lexical_Frame
     */
    public Lexical_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lexical_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        start_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        error_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        token_table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        id_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        read_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_area.setColumns(20);
        text_area.setRows(5);
        jScrollPane1.setViewportView(text_area);

        jLabel1.setText("文本区");

        start_button.setText("词法分析");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        clear_button.setText("清空文本");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        error_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "错误类型", "行数"
            }
        ));
        jScrollPane2.setViewportView(error_table);

        jLabel2.setText("错误提示");

        jLabel3.setText("词法单元");

        token_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "原始单词", "种别", "属性值", "备注", "行数"
            }
        ));
        jScrollPane3.setViewportView(token_table);

        id_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "序号", "值", "首次行数"
            }
        ));
        jScrollPane4.setViewportView(id_table);

        jLabel4.setText("符号表");

        read_button.setText("读取文件");
        read_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lexical_panelLayout = new javax.swing.GroupLayout(lexical_panel);
        lexical_panel.setLayout(lexical_panelLayout);
        lexical_panelLayout.setHorizontalGroup(
            lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lexical_panelLayout.createSequentialGroup()
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lexical_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lexical_panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(read_button)
                                .addGap(72, 72, 72)
                                .addComponent(start_button)
                                .addGap(67, 67, 67)
                                .addComponent(clear_button))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
                        .addGap(79, 79, 79))
                    .addGroup(lexical_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(20, 20, 20))
        );
        lexical_panelLayout.setVerticalGroup(
            lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lexical_panelLayout.createSequentialGroup()
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lexical_panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(start_button)
                                .addComponent(read_button))
                            .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clear_button)
                                .addComponent(jLabel4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lexical_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lexical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lexical_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lexical_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        text_area.setText(null);
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:
        String content = text_area.getText();
        lexical_analysis = new com.hit.core.Lexical();
        lexical_analysis.Lexical_Analysis(content);
        int length = lexical_analysis.Token_List.size();
        Object[][] e1 = new Object[length+10][5];
        Object[][] e2 = new Object[length][3];
        for(int i=0;i<length;i++){
            e1[i][0] = lexical_analysis.Token_List.get(i).value;
            e1[i][1] = Lexical.Token_Code[lexical_analysis.Token_List.get(i).code].toUpperCase();
            e1[i][3] = lexical_analysis.Token_List.get(i).code;
            e1[i][2] = lexical_analysis.Token_List.get(i).true_value;
            e1[i][4] = lexical_analysis.Token_List.get(i).row_number;
        }
        length = lexical_analysis.Sign_List.size();
        for(int i=0;i<length;i++){
            e2[i][0] = i;
            e2[i][1] = lexical_analysis.Sign_List.get(i).value;
            e2[i][2] = lexical_analysis.Sign_List.get(i).row_number;
        }
        length = lexical_analysis.Lexical_Error_List.size();
        Object[][] e3 = new Object[length][2];
        for(int i=0;i<length;i++){
            e3[i][0] =  Lexical.Lexical_Error_State[lexical_analysis.Lexical_Error_List.get(i).code];
            e3[i][1] =  lexical_analysis.Lexical_Error_List.get(i).row_number;
        }
        token_table.setModel(new javax.swing.table.DefaultTableModel(
            e1,
            new String [] {
                "原始单词", "种别", "属性值", "备注", "行数"
            }
        ));
        error_table.setModel(new javax.swing.table.DefaultTableModel(
            e3,
            new String [] {
                "错误类型", "行数"
            }
        ));
        id_table.setModel(new javax.swing.table.DefaultTableModel(
            e2,
            new String [] {
                "序号", "值", "首次行数"
            }
        ));
    }//GEN-LAST:event_start_buttonActionPerformed

    private void read_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fd = new JFileChooser();  
//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);  
         fd.showOpenDialog(null);  
         String temp="";
        File f = fd.getSelectedFile();  
        if(f != null){
            InputStream is = null;  
            try {
                is = new FileInputStream(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Lexical_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        InputStreamReader fr = new InputStreamReader(is);  
        int ch = 0;    
            try {
                while((ch = fr.read())!=-1 ){
                    temp += (char)ch;
                }   } catch (IOException ex) {
                Logger.getLogger(Lexical_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            text_area.setText(temp);
        } 
        
    }//GEN-LAST:event_read_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lexical_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lexical_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lexical_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lexical_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Lexical_Frame().setVisible(true);
            }
        });
    }
    private com.hit.core.Lexical lexical_analysis;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_button;
    private javax.swing.JTable error_table;
    private javax.swing.JTable id_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel lexical_panel;
    private javax.swing.JButton read_button;
    private javax.swing.JButton start_button;
    private javax.swing.JTextArea text_area;
    private javax.swing.JTable token_table;
    // End of variables declaration//GEN-END:variables
}
